spryk: method
description: "Adds a new action to the Yves controller."
mode: both
level: 2

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    theme:
        inherit: true
        default: default

    controller:
        inherit: true
        callback:
            - ClassNameShortCallback
            - EnsureControllerSuffixCallback
        type: ClassNameChoice
        typeOptions:
            - module
            - spryk
            - choiceLoader

    controllerMethod:
        inherit: true
        callback: EnsureActionSuffixCallback

    templateName:
        value: "{{ controllerMethod | removeActionSuffix | dasherize }}"

    template:
        value: Yves/Controller/YvesControllerMethod.php.twig

    target:
        value: "{{ organization }}\\Yves\\{{ module }}\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
    - AddYvesController

postSpryks:
    - AddYvesView
    - AddYvesRouteProviderAction

