spryk: structure
description: "Adds a new Page to the Yves application (Controller with action, router plugin with action and default view)."
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    theme:
        inherit: true
        default: default

    controller:
        inherit: true
        default: Index

    controllerMethod:
        inherit: true
        default: index

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

preSpryks:
    - AddModuleYves
    - AddYvesControllerAction

