spryk: template
description: "Adds a new Widget to the Yves application."
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    widget:
        inherit: true

    widgetClassName:
        value: "{{ widget | removeWidgetSuffix }}Widget"

    templateName:
        value: "{{ widget | removeWidgetSuffix | dasherize }}"

    template:
        value: Yves/YvesWidget.php.twig

    targetFilename:
        value: "{{ widget | removeWidgetSuffix }}Widget.php"

    targetPath:
        value: "src/{{ organization }}/Yves/{{ module }}/Widget/"

preSpryks:
    - AddModule

postSpryks:
    - AddYvesFactory
    - AddYvesWidgetView
