spryk: template
description: "Adds a new *module*To*dependentModule*ClientBridge."
mode: core

arguments:
  organization:
    inherit: true
    default: Spryker

  module:
    inherit: true

  dependentModuleOrganization:
    inherit: true
    default: Spryker

  dependentModule:
    inherit: true

  template:
    value: Glue/Dependency/Client/GlueDependencyClientBridge.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ClientBridge.php"

  targetPath:
    value: "{{ moduleRoot }}/src/{{ organization }}/Glue/{{ module }}/Dependency/Client/"

preSpryks:
  - AddModule

postSpryks:
  - AddGlueDependencyClientInterface
  - AddGlueDependencyClientFactoryMethod
  - AddGlueDependencyClientDependencyProviderMethod
  - AddGlueDependencyClientDependencyProviderConstant:
      arguments:
          name:
            value: "CLIENT_{{ dependentModule | underscored | upper }}"
          value:
            value:  "CLIENT_{{ dependentModule | underscored | upper }}"
          visibility:
            value:  "public"
