spryk: template
description: "Adds a new *module*To*dependentModule*ClientInterface."
mode: both

arguments:
    module:
        inherit: true

    dependentModule:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Glue/Dependency/Client/GlueDependencyClientInterface.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}ClientInterface.php"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/Dependency/Client/"

preSpryks:
    - AddModule
