spryk: template
description: "Adds a new Data Import plugin."
mode: both

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        type: NewModuleType

    entity:
        inherit: true

    template:
        value: Module/DataImport/Zed/Communication/DataImportPlugin.php.twig

    targetFilename:
        value: "{{ entity | dashToCamelCase }}DataImportPlugin.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/Plugin/DataImport/"

preSpryks:
    - AddModule
    - AddZedCommunicationFactory
    - AddZedBusinessFacade
