spryk: template
description: "Adds a new Widget view twig template to the Yves application."
mode: both

config:
    noRender: true

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    theme:
        inherit: true
        default: default

    templateName:
        inherit: true
        default: default

    template:
        value: Yves/Theme/YvesWidgetViewTwig.twig

    targetFilename:
        value: "{{ templateName }}.twig"

    targetPath:
        value: "src/{{ organization }}/Yves/{{ module }}/Theme/{{ theme }}/views/{{ templateName }}/"

preSpryks:
    - AddModule
