language: php

sudo: false

php:
  - 7.1

env:
  global:
  - DEFAULT=1 CI=1

matrix:
  include:
  - php: 7.1
    env: PREFER_LOWEST=1

  - php: 7.3
    env: COVERAGE=1 DEFAULT=0

  - php: 7.2
    env: CHECKS=1 DEFAULT=0

    fast_finish: true

before_install:
  - if [[ $COVERAGE != 1 ]]; then phpenv config-rm xdebug.ini; fi
  - composer global require hirak/prestissimo
  - phpenv config-add ci/travis.php.ini

before_script:
  - php -ini | grep memory_limit
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --no-interaction; fi;
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --no-interaction --prefer-dist --prefer-stable; fi;

script:
  - php -ini | grep memory_limit
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run -g Glue; fi
  - php -ini | grep memory_limit
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/codecept run -x Glue; fi
  - if [[ $COVERAGE == 1 ]]; then vendor/bin/codecept run --coverage-xml; fi

  - if [[ $CHECKS == 1 ]]; then composer phpstan ; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-check ; fi

notifications:
    email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

after_success:
    - if [[ $COVERAGE == 1 ]]; then travis_retry php vendor/bin/coveralls; fi
