spryk: template
description: "Adds a new .gitattributes to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: gitattributes.twig

    targetFilename:
        value: .gitattributes

    targetPath:
        value: ""

preSpryks:
    - AddModule
