spryk: template
description: "Adds a new CI config to the module."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: ci.yml.twig

    targetFilename:
        value: ci.yml

    targetPath:
        value: ".github/workflows/"

preSpryks:
    - AddModule
