spryk: template
description: "Adds a new codeception.yml to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: codeception.yml.twig

    targetPath:
        value: ""

preSpryks:
    - AddModule
    - AddModuleTest
