spryk: template
description: "Adds a new .editorconfig to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: editorconfig.twig

    targetFilename:
        value: .editorconfig

    targetPath:
        value: ""

preSpryks:
    - AddModule
