spryk: template
description: "Adds a new .scrutinizer.yml to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: scrutinizer.yml.twig

    targetFilename:
        value: .scrutinizer.yml

    targetPath:
        value: ""

preSpryks:
    - AddModule
