spryk: template
description: "Adds a new phpstan.neon to the Modules root."
mode: core

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: phpstan.neon.twig

    targetPath:
        value: ""

preSpryks:
    - AddModule
