spryk: method
description: "Adds a new method to the *target* processor model interface."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  className:
    inherit: true

  subDirectory:
    inherit: true
    isOptional: true

  method:
    inherit: true

  input:
    inherit: true

  output:
    inherit: true

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: '{{ organization }}\Glue\{{ module }}\Processor{% if subDirectory %}\{{ subDirectory }}{% endif %}\{{ className }}Interface'

preSpryks:
  - AddGlueProcessorModel

postSpryks:
  - AddGlueProcessorModelMethod
