spryk: template
description: "Adds a new Processor model to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    constructorArguments:
        type: GlueProcessorDependency
        typeOptions:
            - module
            - spryk
        isOptional: true
        isMultiple: true

    interfaceName:
        inherit: true
        value: "{{ className }}Interface"
        callback:
            - EnsureInterfaceSuffix

    template:
        value: Glue/Processor/GlueProcessorModel.php.twig

    targetFilename:
        callbackOnly: true
        callback: GlueProcessorModelTargetFilename

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/Processor/"

preSpryks:
    - AddModule

postSpryks:
    - AddGlueProcessorModelInterface
    - AddGlueFactoryMethod
