spryk: template
description: "Adds a new Console command to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    className: ~

    consoleCommand: ~

    template:
        value: Zed/Communication/Console/ZedCommunicationConsole.php.twig

    targetFilename:
        value: "{{ className }}Console.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/Console/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedCommunicationConsoleTest
