spryk: template
description: "Adds a new Route provider to the Yves application."
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    template:
        value: Yves/RouteProvider/YvesRouteProvider.php.twig

    targetFilename:
        value: "{{ module }}RouteProviderPlugin.php"

    targetPath:
        value: "src/{{ organization }}/Yves/{{ module }}/Plugin/Router/"

preSpryks:
    - AddModule

