spryk: template
description: "Adds a new Business model to the Zed application."
mode: both

application: Zed
layer: Business

priority: 1

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    constructorArguments:
        isOptional: true
        isMultiple: true

    interfaceName:
        default: \Spryker\Zed\DataImport\Business\Model\DataImportStep\DataImportStepInterface

    template:
        value: Module/DataImport/Zed/Business/Model/DataImportZedBusinessModel.php.twig

    targetFilename:
        callbackOnly: true
        callback: ZedBusinessModelTargetFilenameCallback

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessFactoryMethod

