spryk: structure
description: "Adds a new PATCH Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  clientModule:
    inherit: true

  clientMethod:
    inherit: true

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

  directories:
    value:
      - ""

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceRoute:
      arguments:
        modelSuffix:
          value: "Updater"
        resourceRouteMethod:
          value: "patch"
  - AddGlueDependencyClientBridgeMethod:
      arguments:
        dependentModule:
          value: "{{ clientModule }}"
        methods:
          value: [ "{{ clientMethod }}" ]
  - AddGlueFactoryMethod:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}Updater"
        subDirectory:
          value: "{{ resourceType | dashToCamelCase | singularize }}"
        dependencyMethods:
          value: [ "get{{ clientModule }}Client" ]
  - AddGlueProcessorModel:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}Updater"
        subDirectory:
          value: "{{ resourceType | dashToCamelCase | singularize }}"
        constructorArguments:
          value: [ "\\{{ organization }}\\Glue\\{{ module }}\\Dependency\\Client\\{{ module }}To{{ clientModule }}ClientInterface ${{ clientModule | lcfirst }}Client" ]
  - AddGlueControllerPatchAction:
      arguments:
        controllerMethod:
          value: "{{ resourceRouteMethod }}"
          callback: EnsureActionSuffixCallback
        controller:
          value: "{{ resourceType | dashToCamelCase }}"
          callback: EnsureResourceSuffix
        target:
          value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ resourceType | dashToCamelCase }}"
          callback:
            - EnsureResourceSuffix
            - EnsureControllerSuffixCallback
