spryk: structure
description: "Adds a new DELETE Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    resourceType:
        inherit: true
        value: "{{ module | removeRestApiSuffix | lower }}"

    clientModule:
        inherit: true

    clientMethod:
        inherit: true

    resourceRouteMethod:
        value: "delete"

    targetPath:
        value: "src/{{ organization }}/Glue/{{ module }}/"

    directories:
        skipOnProjectLevel: true
        value:
            - ""

preSpryks:
    - AddModule
    - AddGlueResourceRoute:
        arguments:
            modelName:
                value: "{{ resourceType | dashToCamelCase | singularize }}"
            modelSuffix:
                value: "Deleter"
    - AddGlueDependencyClientBridgeMethod:
        arguments:
            dependentModule:
                value: "{{ clientModule }}"
            methods:
                value: [ "{{ clientMethod }}" ]
    - AddGlueFactoryMethod:
        arguments:
            className:
                value: "{{ resourceType | dashToCamelCase | singularize }}Deleter"
            subDirectory:
                value: "{{ resourceType | dashToCamelCase | singularize }}"
            dependencyMethods:
                value: [ "get{{ clientModule }}Client" ]
    - AddGlueProcessorModel:
        arguments:
            className:
                value: "{{ resourceType | dashToCamelCase | singularize }}Deleter"
            subDirectory:
                value: "{{ resourceType | dashToCamelCase | singularize }}"
            constructorArguments:
                value: [ "\\{{ organization }}\\Glue\\{{ module }}\\Dependency\\Client\\{{ module }}To{{ clientModule }}ClientInterface ${{ clientModule | lcfirst }}Client" ]
    - AddGlueControllerDeleteAction:
        arguments:
            controllerMethod:
                value: "{{ resourceRouteMethod }}"
                callback: EnsureActionSuffixCallback
            controller:
                value: "{{ resourceType | dashToCamelCase }}"
                callback: EnsureResourceSuffix
            target:
                value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ resourceType | dashToCamelCase }}"
                callback:
                    - EnsureResourceSuffix
                    - EnsureControllerSuffixCallback
