spryk: method
description: "Adds a facade dependency method to the *module*DependencyProvider."
mode: both

arguments:
    module:
        inherit: true
        moduleFilter:
            application: Zed

    dependentModule:
        inherit: true
        moduleFilter:
            application: Zed

    organization:
        inherit: true
        default: Spryker

    providerMethod:
        value: "add{{ dependentModule }}Facade"

    template:
        value: Zed/Dependency/Facade/ZedDependencyFacadeDependencyProviderMethod.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
    - AddZedDependencyProvider
    - AddZedDependencyProviderProvideMethod:
          arguments:
                layer:
                    value: Business

postSpryks:
    - AddZedDependencyFacadeToDependencyProvider:
          arguments:
              provideMethod:
                  value: "provideBusinessLayerDependencies"

    - AddZedDependencyFacadeDependencyProviderConstant:
        arguments:
            name:
                value: "FACADE_{{ dependentModule | camelCaseToUnderscore | upper }}"
            value:
                value: "FACADE_{{ dependentModule | camelCaseToUnderscore | upper }}"
            visibility:
                value: "public"

