spryk: method
description: "Adds a facade dependency method to the *module*DependencyProvider."
mode: both

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    inherit: true
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  method:
    value: "add{{ dependentModule }}Facade"

  template:
    value: Zed/Dependency/Facade/ZedDependencyFacadeDependencyProviderMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
  - AddZedDependencyProvider

postSpryks:
  - AddZedDependencyFacadeBridge
  - AddZedDependencyFacadeDependencyProviderConstant:
      arguments:
        name:
          value: "FACADE_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} facade"
        visibility:
          value:  "public"

