spryk: bridgeMethods
description: "Adds a new method to the *module* dependency facade bridge interface."
mode: "core|sdk|eco"

arguments:
  module:
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  dependentModule:
    inherit: true
    moduleFilter:
      application: Zed

  methods:
    type: MethodNameChoice
    choiceLoader: ZedFacadeMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeInterfaceMethod.php.twig

  dependencyType:
    value: Facade

  sourceClass:
    value: "{{ organization }}\\Zed\\{{ dependentModule }}\\Business\\{{ dependentModule }}FacadeInterface"

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Dependency\\Facade\\{{ module }}To{{ dependentModule }}FacadeInterface"

preSpryks:
  - AddZedDependencyFacadeInterface

postSpryks:
  - AddZedDependencyFacadeBridgeMethod


