spryk: template
description: "Adds a new *module*To*dependentModule*FacadeBridge."
mode: core

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        moduleFilter:
            application: Zed

    dependentModuleOrganization:
        inherit: true
        default: Spryker

    dependentModule:
        inherit: true
        moduleFilter:
            application: Zed

    template:
        value: Zed/Dependency/Facade/ZedDependencyFacadeBridge.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}FacadeBridge.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Dependency/Facade/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedDependencyFacadeInterface
    - AddZedDependencyFacadeBusinessFactoryMethod
    - AddZedDependencyFacadeDependencyProviderMethod
