spryk: method
description: "Adds a facade dependency method to the *module*BusinessFactory."
mode: both

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  method:
    value: "get{{ dependentModule }}Facade"

  template:
    value: Zed/Dependency/Facade/ZedDependencyFacadeBusinessFactoryMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
  - AddZedBusinessFactory

postSpryks:
  - AddZedDependencyFacadeDependencyProviderConstant:
      arguments:
        name:
          value: "FACADE_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} facade"
        visibility:
          value:  "public"
