spryk: bridgeMethods
description: "Adds a new method to the *module* dependency facade bridge."
priority: 1
mode: core
level: 2

arguments:
  module:
    inherit: true
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  dependentModule:
    inherit: true
    moduleFilter:
      application: Zed

  methods:
    type: MethodNameChoice
    choiceLoader: ZedFacadeMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeMethod.php.twig

  dependencyType:
    value: Facade

  sourceClass:
    value: "{{ organization }}\\Zed\\{{ dependentModule }}\\Business\\{{ dependentModule }}Facade"

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Dependency\\Facade\\{{ module }}To{{ dependentModule }}FacadeBridge"

preSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyFacadeBridge

postSpryks:
  - AddZedDependencyFacadeBridgeInterfaceMethod
