arguments:
  sprykerVendorPath:
      value: "spryker/"
  moduleSrcDirectory:
      value: "Bundles/"
  repository:
    value: "{{ sprykerVendorPath }}{{ organization | dasherize }}"
  moduleRoot:
    value: "{{ module }}"
  level:
    value: 3

core:
  arguments:
    mode:
      value: "core"
      type: "default"
    targetPath:
      value: "vendor/{{ repository }}/{{ moduleSrcDirectory }}"
      type: prepend

project:
  arguments:
    mode:
      value: "project"
      type: "default"
    targetPath:
      value: "src/{{ organization }}/{{ layer }}/"
      type: prepend
