spryk: template
description: "Adds a new *Module*ServiceInterface to the Service application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Service/ServiceInterface.php.twig

    targetFilename:
        value: "{{ module }}ServiceInterface.php"

    targetPath:
        value: "src/{{ organization }}/Service/{{ module }}/"

preSpryks:
    - AddService
