spryk: method
description: "Adds a Service dependency method to the *module*Factory."
mode: both

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    dependentModule:
        inherit: true
        moduleFilter:
            application: Service

    factoryMethod:
        value: "get{{ dependentModule }}Service"

    template:
        value: Client/Dependency/Service/ClientDependencyServiceFactoryMethod.php.twig

    target:
        value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}Factory"

preSpryks:
    - AddClientDependencyProvider
    - AddClientFactory

postSpryks:
    - AddConstant:
        arguments:
            name:
                value: "SERVICE_{{ dependentModule | underscored | upper }}"
            value:
                value: "SERVICE_{{ dependentModule | underscored | upper }}"
            visibility:
                value: "public"
            target:
                value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}DependencyProvider"
