spryk: structure
description: "Adds a new *module* Business test suite directory."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "tests/{{ organization }}Test/Zed/{{ module }}/Business/"

postSpryks:
    - AddZedBusinessTestSuiteConfiguration
    - AddZedBusinessTester
    - AddZedTestHelper
