spryk: update-yml
description: "Updates the *module* test configuration and adds the suite configuration for Business tests."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Business/ZedBusinessTestSuiteCodeceptionConfiguration.yml.twig

    afterElement:
        value: coverage

    addToElement:
        value: suites

    targetPath:
        value: "tests/{{ organization }}Test/Zed/{{ module }}/codeception.yml"

preSpryks:
    - AddZedTestCodeceptionConfiguration
