spryk: template
description: "Adds a new Abstract*tableName*Query class to Zed's persistence layer."
mode: "all"

arguments:
  module:
    inherit: true
  targetModule: ~
  tableName: ~

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/Propel/AbstractQuery.php.twig

  targetFilename:
    value: "Abstract{{ tableName | camelCased }}Query.php"

  targetPath:
    value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/"

preSpryks:
  - AddZedPersistencePropelSchemaTable

postSpryks:
  - AddZedPersistencePropelAbstractEntity
