spryk: template
description: "Adds a new Abstract*tableName* class to Zed's persistence layer."
mode: both

arguments:
  module:
    inherit: true
  targetModule: ~
  tableName: ~

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/Propel/AbstractEntity.php.twig

  targetFilename:
    value: "Abstract{{ tableName | camelCased }}.php"

  targetPath:
    value: "{{ moduleRoot }}/src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/"

preSpryks:
  - AddZedPersistencePropelSchemaTable

postSpryks:
  - AddZedPersistencePropelAbstractQuery
