spryk: template
description: "Adds a new Abstract*tableName* class to Zed's persistence layer."
mode: both

arguments:
    module:
        inherit: true

    targetModule:
        inherit: true

    tableName:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Persistence/Propel/AbstractEntity.php.twig

    targetFilename:
        value: "Abstract{{ tableName | camelCased }}.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/"

preSpryks:
    - AddZedPersistencePropelSchemaTable

postSpryks:
    - AddZedPersistencePropelAbstractQuery
