spryk: template
description: "Adds a new *module*To*dependentModule*ClientInterface."
mode: both

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    dependentModule:
        inherit: true
        moduleFilter:
            application: Client

    template:
        value: Client/Dependency/Client/ClientDependencyClientInterface.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}ClientInterface.php"

    targetPath:
        value: "src/{{ organization }}/Client/{{ module }}/Dependency/Client/"

preSpryks:
    - AddModule
