spryk: method
description: "Adds a Client dependency method to the *module*Factory."
mode: both

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    dependentModule:
        inherit: true

    factoryMethod:
        value: "get{{ dependentModule }}Client"

    template:
        value: Client/Dependency/Client/ClientDependencyClientFactoryMethod.php.twig

    target:
        value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}Factory"

preSpryks:
    - AddClientDependencyProvider
    - AddClientFactory

postSpryks:
    -   AddConstant:
            arguments:
                name:
                    value: "CLIENT_{{ dependentModule | underscored | upper }}"
                value:
                    value:  "CLIENT_{{ dependentModule | underscored | upper }}"
                visibility:
                    value:  "public"
                target:
                    value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}DependencyProvider"

