spryk: schema
description: "Adds a new table to the spy_*targetModule*.schema.xml."
mode: both

arguments:
    module:
        inherit: true

    targetModule:
        inherit: true

    tableName:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/Schema/spy_{{ targetModule | underscored }}.schema.xml"

preSpryks:
    - AddZedPersistencePropelSchema

postSpryks:
    - AddZedPersistencePropelAbstractEntity
    - AddZedPersistencePropelAbstractQuery
