spryk: template
description: "Adds a new AsyncAPI file to the specified `targetFile` path."
priority: 1
mode: both
level: 2

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true

    template:
        value: App/Common/Api/AsyncApi/asyncapi.schema.yml.twig

    targetPath:
        value: "config/api/asyncapi/"

    targetFilename:
        required: true
        default: asyncapi.yml

    title:
        required: true

    apiVersion:
        default: 0.1.0
