spryk: template
description: "Adds a new twig file to the *module* Presentation layer."
mode: both
level: 2

config:
    noRender: true

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    controller:
        inherit: true
        callback:
            - ClassNameShortCallback
            - RemoveControllerSuffixCallback

    controllerMethod:
        inherit: true
        callback:
            - RemoveActionSuffixCallback

    template:
        value: Zed/Presentation/ZedPresentationTwig.twig

    targetFilename:
        value: "{{ controllerMethod | removeActionSuffix | dasherize | lcfirst }}.twig"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Presentation/{{ controller | classNameShort | removeControllerSuffix }}/"
