spryk: structure
description: "Adds a new *module* structure with Zed (all layers stubs facades, factories), Client, Transfer skeletons."
priority: 1
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        type: NewModuleType

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

postSpryks:
    - AddModule
    - AddClient
    - AddClientConfig
    - AddSharedTransferSchema
    - AddZedConfig
    - AddZedDependencyProvider
    - AddZedBusinessFacade
    - AddZedCommunicationFactory
    - AddZedPersistenceEntityManager
    - AddZedPersistenceRepository
    - AddZedTestCodeceptionConfiguration
    - AddZedTestSuiteToCodeceptionConfiguration
