spryk: structure
description: "Adds a new Util *module* structure."
priority: 1
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        type: NewModuleType

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

postSpryks:
    - AddModule
    - AddSharedTransferSchema
    - AddService
