spryk: structure
description: "Adds a new Data Import module structure. Property entity must be in camel case."
priority: 1
mode: both
level: 1

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        type: NewModuleType

    entity:
        inherit: true

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

preSpryks:
    - AddModule

postSpryks:
    - AddSharedTransferSchema
    - AddSharedTransferDefinition:
        arguments:
            name:
                value: DataImporterConfiguration
    - AddSharedTransferDefinition:
        arguments:
            name:
                value: DataImporterReport
    - AddZedConfig:
        arguments:
            extends:
                value: \Spryker\Zed\DataImport\DataImportConfig
    - AddZedDependencyProvider:
        arguments:
            extends:
                value: \Spryker\Zed\DataImport\DataImportDependencyProvider
    - AddDataImportZedBusinessFactoryMethod
    - AddZedBusinessFacade
    - AddZedConfigMethod:
        arguments:
            configMethod:
                value: "get{{ entity }}DataImporterConfiguration"
            input:
                value: ""
            output:
                value: \Generated\Shared\Transfer\DataImporterConfigurationTransfer
    - AddConstant:
        arguments:
            name:
                value: "IMPORT_TYPE_{{ entity | underscored | upper }}"
            value:
                value: "{{ entity | dasherize }}"
            visibility:
                value: "public"
            target:
                value: "\\{{ organization }}\\Zed\\{{ module }}\\{{ module }}Config"
    - AddZedBusinessFacadeMethod:
        arguments:
            facadeMethod:
                value: "import{{ entity }}"
            input:
                value: "?\\Generated\\Shared\\Transfer\\DataImporterConfigurationTransfer $dataImporterConfigurationTransfer = null"
            output:
                value: \Generated\Shared\Transfer\DataImporterReportTransfer
            body:
                value: "return $this->getFactory()->get{{ entity }}DataImporter()->import($dataImporterConfigurationTransfer);"
    - AddDataImportZedBusinessWriterStepMethod:
        arguments:
            className:
                value: "{{ entity }}DataImportWriterStep"
            subDirectory:
                value: "DataImportStep"
            modelMethod:
                value: "execute"
            input:
                value: "\\Spryker\\Zed\\DataImport\\Business\\Model\\DataSet\\DataSetInterface $dataSet"
            output:
                value: void
    - AddZedCommunicationFactory
    - AddDataImportPlugin
    - AddZedPersistenceEntityManager
    - AddZedPersistenceRepository
    - AddZedTestCodeceptionConfiguration
    - AddZedTestSuiteToCodeceptionConfiguration
