spryk: template
description: "Adds a new phpstan.json to the Modules root."
mode: core

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: phpstan.json.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
