spryk: structure
description: "Adds a new payment module structure."
priority: 1
mode: both
level: 1

arguments:
    organization:
        default: SprykerEco

    module:
        inherit: true
        type: NewModuleType

    paymentMethod:
        inherit: true

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

    classNamePrefix:
        value: '{{ paymentMethod | ucfirst }}'

preSpryks:
    - AddModule

postSpryks:
    - AddYvesFactory
    - AddCheckoutPostSavePluginMethod
    - AddCheckoutDoSaveOrderPluginMethod
    - AddPaymentMethodFilterPluginMethod
    - AddCheckoutPreConditionPluginMethod
    - AddOrderPaymentExpanderPluginMethod
    - AddCommandByOrderPluginMethod
    - AddSubFormPluginMethod
    - AddSubFormPluginDataProviderMethod
