spryk: structure
description: "Adds a new *module* structure."
priority: 1
mode: both

arguments:
    organization:
        inherit: true
        default: Spryker

    module:
        inherit: true
        type: NewModuleType

    targetPath:
        value: "{{ module }}/"

    directories:
        value:
            - "src/{{ organization }}/"

postSpryks:
    - AddModuleReadme
    - AddModuleComposerJson
    - AddModuleLicense
    - AddModuleContributing
    - AddModuleChangelog
    - AddModuleTravis
    - AddModuleGitattributes
    - AddModuleGitignore
    - AddModuleTooling
    - AddModulePhpStanJson
    - AddModulePhpStanNeon
    - AddModuleEditorconfig
