spryk: structure
description: "Adds a new *module* with Yves classes structure. Preferable to use AddYvesPage, AddYvesWidget"
priority: 1
mode: both
level: 2

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true
        type: NewModuleType

    theme:
        inherit: true
        default: default

    targetPath:
        value: ""

    directories:
        skipOnProjectLevel: true
        value:
            - "src/{{ organization }}/"

postSpryks:
    - AddModule
    - AddSharedTransferSchema
    - AddYvesFactory
    - AddYvesDependencyProvider
    - AddYvesConfig
    - AddYvesTheme
