spryk: method
description: "Adds a new method to the *target* business model interface."
mode: both

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  className: ~

  method:
    inherit: true

  input:
    inherit: true

  output:
    inherit: true


  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ className }}Interface"

preSpryks:
  - AddZedBusinessModel:
      arguments:
        subDirectory:
          callback: ZedBusinessModelSubDirectoryCallback

        className:
          callback: ClassNameShortCallback

postSpryks:
  - AddZedBusinessModelMethod
