spryk: method
description: "Adds a new method to the *target* business model."
mode: both

application: Zed
layer: Business

priority: 1

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  className:
    type: ClassNameChoice
    choiceLoader: ZedBusinessModelChoiceLoader
    typeOptions:
      - module
      - spryk
      - choiceLoader

  method: ~

  input:
    isOptional: true
    isMultiple: true

  output:
    isOptional: true

  facadeMethod:
    default: "{{ method }}"

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ className }}"

preSpryks:
  - AddZedBusinessModel:
      arguments:
        subDirectory:
          callback: ZedBusinessModelSubDirectoryCallback

        className:
          callback: ClassNameShortCallback

postSpryks:
  - AddZedBusinessModelInterfaceMethod
  - AddZedBusinessFacadeMethod:
      isOptional: true
      arguments:
        method:
          value: "{{ facadeMethod }}"
