spryk: template
description: "Adds a new Business model to the Zed application."
mode: both
level: 2

application: Zed
layer: Business

priority: 1

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    subDirectory:
        inherit: true
        isOptional: true

    className:
        inherit: true

    constructorArguments:
        type: ZedBusinessDependency
        typeOptions:
            - module
            - spryk
        isOptional: true
        isMultiple: true

    interfaceName:
        value: "{{ className }}Interface"

    template:
        value: Zed/Business/Model/ZedBusinessModel.php.twig

    targetFilename:
        callbackOnly: true
        callback: ZedBusinessModelTargetFilenameCallback

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessModelInterface
    - AddZedBusinessFactoryMethod

