spryk: template
description: "Adds a new *module*CommunicationFactory to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Communication/ZedCommunicationFactory.php.twig

    targetFilename:
        value: "{{ module }}CommunicationFactory.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/"

preSpryks:
    - AddModule
