spryk: template
description: "Adds a new Test to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    className:
        inherit: true

    template:
        value: Zed/Communication/ZedCommunicationTest.php.twig

    targetFilename:
        value: "{{ className }}Test.php"

    targetPath:
        value: "tests/{{ organization }}Test/Zed/{{ module }}/Communication/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedCommunicationTestSuite
