spryk: navigation
description: "Adds a new navigation node entry tho the *module* navigation.xml."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    controller:
        inherit: true
        callback:
            - ClassNameShortCallback
            - RemoveControllerSuffixCallback

    controllerMethod:
        inherit: true
        callback:
            - RemoveActionSuffixCallback

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/navigation.xml"

preSpryks:
    - AddZedNavigationSchema
