spryk: template
description: "Adds a new navigation.xml to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Communication/navigation.xml.twig

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/"

preSpryks:
    - AddModule
