spryk: method
description: "Adds a new action to the Zed controller."
mode: both
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    controller:
        inherit: true
        callback:
            - ClassNameShortCallback
            - EnsureControllerSuffixCallback
        type: ClassNameChoice
        choiceLoader: ZedCommunicationControllerChoiceLoader
        typeOptions:
            - module
            - spryk
            - choiceLoader

    controllerMethod:
        inherit: true
        callback: EnsureActionSuffixCallback

    output:
        default: void

    template:
        value: Zed/Communication/MethodZedCommunicationController.php.twig

    target:
        value: "{{ organization }}\\Zed\\{{ module }}\\Communication\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
    - AddZedCommunicationController

postSpryks:
    - AddZedPresentationTwig
    - AddZedNavigationNode

