spryk: template
description: "Adds a new Gateway Controller to the Zed application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Zed/Communication/ZedCommunicationController.php.twig

    controller:
        value: GatewayController

    targetFilename:
        value: "GatewayController.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Communication/Controller/"

preSpryks:
    - AddModule

