spryk: method
description: "Adds a new method to the *module*EntityManager."
mode: "all"

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  entityManagerMethod: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}EntityManager"

preSpryks:
  - AddZedPersistenceEntityManager

postSpryks:
  - AddZedPersistenceEntityManagerInterfaceMethod
