spryk: method
description: "Adds a new method to the *module*EntityManagerInterface."
mode: "all"

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  entityManagerMethod:
    inherit: true

  input:
    inherit: true

  output:
    inherit: true


  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}EntityManagerInterface"

preSpryks:
  - AddZedPersistenceEntityManagerInterface
