spryk: template
description: "Adds a new *module*To*dependentModule*ServiceBridge."
mode: core

arguments:
  module:
    moduleFilter:
      application: Zed

  organization:
    inherit: true
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Service

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Zed/Dependency/Service/ZedDependencyServiceBridge.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ServiceBridge.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Dependency/Service/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedDependencyServiceInterface
  - AddZedDependencyServiceBusinessFactoryMethod
  - AddZedDependencyServiceDependencyProviderMethod
  - AddZedDependencyServiceDependencyProviderConstant:
      arguments:
          name:
            value: "SERVICE_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
          visibility:
            value:  "public"
