spryk: method
description: "Adds a new method to the Client *module*Config."
mode: "all"

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  comment:
    multiline: true
    isOptional: true

  configMethod: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}Config"

preSpryks:
  - AddClientConfig

