spryk: template
description: "Adds a new *Module*ClientInterface to the Client application."
mode: both

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Client/ClientInterface.php.twig

    targetFilename:
        value: "{{ module }}ClientInterface.php"

    targetPath:
        value: "src/{{ organization }}/Client/{{ module }}/"

preSpryks:
    - AddClient
