spryk: template
description: "Adds a new *module*ConstantsInterface to the Shared application."
mode: both
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Spryker

    template:
        value: Shared/SharedConstantsInterface.php.twig

    targetFilename:
        value: "{{ module }}Constants.php"

    targetPath:
        value: "src/{{ organization }}/Shared/{{ module }}/"

preSpryks:
    - AddModule
