spryk: template
description: "Adds a new *module*To*dependentModule*ServiceInterface."
mode: both

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    dependentModule:
        inherit: true

    template:
        value: Yves/Dependency/Service/YvesDependencyServiceInterface.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}ServiceInterface.php"

    targetPath:
        value: "{{ moduleRoot }}/src/{{ organization }}/Yves/{{ module }}/Dependency/Service/"

preSpryks:
    - AddYvesDependencyServiceBridge
