spryk: template
description: "Adds a new *module*To*dependentModule*ServiceBridge."
mode: core

arguments:
    organization:
        inherit: true
        default: SprykerShop

    module:
        inherit: true

    dependentModule:
        inherit: trues

    dependentModuleOrganization:
        default: Spryker

    template:
        value: Yves/Dependency/Service/YvesDependencyServiceBridge.php.twig

    targetFilename:
        value: "{{ module }}To{{ dependentModule }}ServiceBridge.php"

    targetPath:
        value: "{{ moduleRoot }}/src/{{ organization }}/Yves/{{ module }}/Dependency/Service/"

preSpryks:
    - AddModule

postSpryks:
    - AddYvesDependencyServiceInterface
    - AddYvesDependencyServiceFactoryMethod
    - AddYvesDependencyServiceDependencyProviderMethod
    -   AddYvesDependencyServiceDependencyProviderConstant:
            arguments:
                name:
                    value: "SERVICE_{{ dependentModule | underscored | upper }}"
                value:
                    value:  "SERVICE_{{ dependentModule | underscored | upper }}"
                visibility:
                    value:  "public"
