spryk: method
description: "Adds a new delete action to the Glue controller."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - EnsureControllerSuffixCallback

  controllerMethod:
    default: "deleteAction"
    callback: EnsureActionSuffixCallback

  resourceType:
    inherit: true

  modelName:
    inherit: true
    default: "{{ resourceType | dashToCamelCase | singularize }}"

  modelSuffix:
    inherit: true
    default: "Deleter"

  template:
    value: Glue/Controller/MethodDeleteGlueController.php.twig

  target:
    value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
  - AddGlueController
  - AddGlueProcessorModelMethod:
      arguments:
        className:
          value: "{{ modelName }}{{ modelSuffix }}"
        input:
          value: "\\Spryker\\Glue\\GlueApplication\\Rest\\Request\\Data\\RestRequestInterface $restRequest"
        output:
          value: "\\Spryker\\Glue\\GlueApplication\\Rest\\JsonApi\\RestResponseInterface"
        method:
          value: "delete{{ modelName }}"
        subDirectory:
          value: "{{ modelName }}"
