arguments:
  sprykerVendorPath:
      value: ""
  moduleSrcDirectory:
      value: ""
  repository:
    value: "{{ sprykerVendorPath }}{{ organization | dasherize }}"
  moduleRoot:
    value: "{{ module | dasherize }}"
  level:
    value: 3

core:
  arguments:
    mode:
      value: "core"
    targetPath:
      value: "vendor/{{ repository }}/{{ moduleSrcDirectory }}"
      type: prepend

project:
  arguments:
    mode:
      value: "project"
    targetPath:
      value: "src/{{ organization }}/{{ layer }}/"
      type: prepend
